# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '08_Covid19_Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.4'
  pod 'Charts'

  # Pods for 08_Covid19_Clone

end
